### ISSUE TITLE
Compile into standalone binary?

### ISSUE THREAD

**Issue by neontorrent** [zhou0/shadowsocks-perl#3]
Any plan to compile into binary using rperl?

This package takes a lot of effort to install - many dependencies, some of which cannot be resolved by cpan and have to be manually fixed and installed.

Or can the dependency be reduced?

**Comment by zhou0** [comment]
Hello!

Running cpan Net::Shadowsocks should pull all the dependencies and build / install this package.  what problem do you get which need to be fixed manually?  

It depends on your platform.  on Unix like systems, you can use Perl packager , see https://metacpan.org/release/RSCHUPP/PAR-Packer-1.039  I have personally tested and it works. I have not tested  this  on windows however. 

To support all the ciphers required by  https://shadowsocks.org/en/spec/AEAD-Ciphers.html and https://shadowsocks.org/en/spec/Stream-Ciphers.html  this package requires a lot of dependencies.  It can be reduced and it is a main goal for next release.   

Hope it helps.
